# Generated by Django 5.2.16 on 2026-08-14 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del curso/grupo (ej: Grado 6A, Sexto uno)', max_length=100)),
                ('level', models.CharField(help_text='Nivel académico (ej: Básica Secundaria, Media Académica)', max_length=100)),
                ('degree', models.CharField(blank=True, help_text='Grado académico (ej: 6º, 7º)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director', models.ForeignKey(blank=True, help_text='Director de grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curriculum_courses',
            },
        ),
    ]
