# Generated by Django 5.2.16 on 2026-08-14 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del área (ej: Ciencias Naturales, Matemáticas)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del área', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'curriculum_areas',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la asignatura (ej: Biología, Física, Química)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción de la asignatura', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(help_text='Área a la que pertenece la asignatura', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='curriculum.area')),
                ('courses', models.ManyToManyField(blank=True, help_text='Cursos en los que se dicta esta asignatura', related_name='subjects', to='curriculum.course')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'curriculum_subjects',
            },
        ),
    ]
