# Generated by Django 5.2.16 on 2026-08-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_area_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Indica si es un área obligatoria Ley 115'),
        ),
    ]
