# Generated by Django 5.2.16 on 2026-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_area_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='weekly_hours',
            field=models.PositiveIntegerField(default=1, help_text='Intensidad horaria semanal máxima permitida por curso'),
        ),
    ]
