# Generated by Django 5.2.17 on 2026-08-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_subject_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='weekly_hours_overrides',
            field=models.JSONField(blank=True, default=dict, help_text="Overrides de horas semanales por grado. Ej: {'10º': 2}"),
        ),
    ]
