# Generated by Django 5.2.17 on 2026-08-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_subject_weekly_hours_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shift',
            field=models.CharField(blank=True, help_text='Jornada (ej. Mañana, Tarde)', max_length=50, null=True),
        ),
    ]
