# Generated by Django 5.2.17 on 2026-08-17 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_course_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='titular',
            field=models.ForeignKey(blank=True, help_text='Docente titular (dicta la mayoría de materias)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
