import React, { useState } from "react";
import { X, Cpu, AlertTriangle, Check, Loader2 } from "lucide-react";
import type { Course } from "@/features/curriculum/types";

interface AutoGenerateDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onGenerate: (courses: number[] | undefined, overwrite: boolean) => Promise<any>;
  courses: Course[];
}

export function AutoGenerateDialog({ isOpen, onClose, onGenerate, courses }: AutoGenerateDialogProps) {
  const [targetType, setTargetType] = useState<"all" | "specific">("all");
  const [selectedCourses, setSelectedCourses] = useState<number[]>([]);
  const [overwrite, setOverwrite] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleToggleCourse = (id: number) => {
    setSelectedCourses(prev =>
      prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]
    );
  };

  const handleGenerate = async () => {
    if (targetType === "specific" && selectedCourses.length === 0) {
      setError("Debe seleccionar al menos un curso.");
      return;
    }
    
    setError(null);
    setIsGenerating(true);
    
    try {
      const targetCourses = targetType === "all" ? undefined : selectedCourses;
      await onGenerate(targetCourses, overwrite);
      onClose();
    } catch (err: any) {
      console.error(err);
      setError(err?.response?.data?.detail || err?.message || "Ocurrió un error al generar el horario.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white dark:bg-slate-900 rounded-3xl max-w-lg w-full border border-slate-200 dark:border-slate-800 shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        <div className="p-6 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-blue-100 dark:bg-blue-900/50 text-blue-600 dark:text-blue-400 rounded-xl">
              <Cpu className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
                Generador de Horarios con IA
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400 font-medium">
                Asignación automática basada en restricciones
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            disabled={isGenerating}
            className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-white/50 dark:hover:bg-slate-800 rounded-full transition-colors disabled:opacity-50"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-6">
          {error && (
            <div className="p-3.5 bg-rose-50 dark:bg-rose-900/20 text-rose-600 dark:text-rose-400 border border-rose-200 dark:border-rose-800/50 rounded-xl text-sm font-semibold flex items-start gap-2">
              <AlertTriangle className="w-5 h-5 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          {/* Scope Selection */}
          <div className="space-y-3">
            <label className="text-sm font-bold text-slate-800 dark:text-slate-200">
              Alcance de la Generación
            </label>
            <div className="grid grid-cols-2 gap-3">
              <button
                type="button"
                onClick={() => setTargetType("all")}
                className={`p-3.5 rounded-2xl border-2 text-left transition-all flex flex-col gap-1 ${
                  targetType === "all"
                    ? "border-blue-500 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 shadow-sm"
                    : "border-slate-200 dark:border-slate-700 hover:border-blue-300 text-slate-600 dark:text-slate-400"
                }`}
              >
                <span className="font-bold text-sm">Toda la Institución</span>
                <span className="text-[10px] opacity-80">Genera para todos los cursos activos</span>
              </button>
              <button
                type="button"
                onClick={() => setTargetType("specific")}
                className={`p-3.5 rounded-2xl border-2 text-left transition-all flex flex-col gap-1 ${
                  targetType === "specific"
                    ? "border-blue-500 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 shadow-sm"
                    : "border-slate-200 dark:border-slate-700 hover:border-blue-300 text-slate-600 dark:text-slate-400"
                }`}
              >
                <span className="font-bold text-sm">Cursos Específicos</span>
                <span className="text-[10px] opacity-80">Selecciona grados particulares</span>
              </button>
            </div>
          </div>

          {targetType === "specific" && (
            <div className="space-y-2 animate-in slide-in-from-top-2 duration-200">
              <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider">
                Seleccione los cursos
              </label>
              <div className="max-h-40 overflow-y-auto p-3 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-700 flex flex-wrap gap-2">
                {courses.map(course => {
                  const isSelected = selectedCourses.includes(course.id);
                  return (
                    <button
                      key={course.id}
                      onClick={() => handleToggleCourse(course.id)}
                      className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all border ${
                        isSelected
                          ? "bg-blue-600 border-blue-600 text-white shadow-sm"
                          : "bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 border-slate-200 dark:border-slate-700 hover:border-slate-400"
                      }`}
                    >
                      {course.name}
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* Overwrite Config */}
          <div className="pt-4 border-t border-slate-100 dark:border-slate-800">
            <label className="flex items-start gap-3 cursor-pointer group">
              <div className="relative inline-flex items-center mt-0.5">
                <input
                  type="checkbox"
                  checked={overwrite}
                  onChange={(e) => setOverwrite(e.target.checked)}
                  className="sr-only peer"
                />
                <div className="w-11 h-6 bg-slate-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-rose-300/50 dark:peer-focus:ring-rose-800/50 rounded-full peer dark:bg-slate-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-slate-600 peer-checked:bg-rose-500"></div>
              </div>
              <div className="flex-1">
                <span className={`text-sm font-bold ${overwrite ? "text-rose-600 dark:text-rose-400" : "text-slate-800 dark:text-slate-200"}`}>
                  Sobrescribir horarios existentes
                </span>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 leading-relaxed">
                  Si activas esta opción, se <strong className="text-rose-500">eliminarán</strong> todas las clases asignadas actualmente en los cursos seleccionados antes de generar el nuevo horario. Si la dejas desactivada, el generador solo llenará los espacios vacíos.
                </p>
              </div>
            </label>
          </div>
        </div>

        <div className="p-6 border-t border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/20 flex justify-end gap-3">
          <button
            onClick={onClose}
            disabled={isGenerating}
            className="px-5 py-2.5 rounded-xl font-bold text-sm text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors disabled:opacity-50"
          >
            Cancelar
          </button>
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="flex items-center gap-2 px-6 py-2.5 rounded-xl font-bold text-sm text-white bg-blue-600 hover:bg-blue-700 shadow-md shadow-blue-500/20 transition-all disabled:opacity-70 disabled:cursor-not-allowed"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Procesando...
              </>
            ) : (
              <>
                <Cpu className="w-4 h-4" />
                Ejecutar Generador
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
