# Generated by Django 5.2.16 on 2026-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('admin', 'Administrador'), ('coordinator', 'Coordinador'), ('teacher', 'Docente'), ('student', 'Estudiante'), ('parent', 'Padre')], default='student', max_length=20),
        ),
    ]
