# Generated by Django 5.2.16 on 2026-08-14 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_user_backup_codes_user_two_factor_enabled_and_more'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
