# Generated by Django 5.2.16 on 2026-08-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0004_user_current_course_user_current_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('pre_enrolled', 'Prematriculado'), ('enrolled', 'Matriculado'), ('withdrawn', 'Retirado'), ('graduated', 'Graduado')], max_length=20, null=True),
        ),
    ]
