# Generated by Django 5.2.16 on 2026-08-14 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('academic_load', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('on_leave', 'En Licencia')], default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Docente',
                'verbose_name_plural': 'Perfiles de Docentes',
                'db_table': 'academics_teacher_profiles',
            },
        ),
    ]
