# Generated by Django 5.2.16 on 2026-08-15 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('curriculum', '0003_area_is_mandatory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('time_slot', models.CharField(help_text='Rango de hora (ej: 07:00 - 08:00)', max_length=50)),
                ('room', models.CharField(blank=True, default='', help_text='Lugar/Aula (ej: Aula 101)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Curso asignado', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='curriculum.course')),
                ('subject', models.ForeignKey(help_text='Asignatura dictada', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='curriculum.subject')),
                ('teacher', models.ForeignKey(help_text='Docente que dicta la clase', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario de Clase',
                'verbose_name_plural': 'Horarios de Clases',
                'db_table': 'academics_class_schedules',
                'unique_together': {('course', 'day', 'time_slot')},
            },
        ),
    ]
