# Generated by Django 5.2.16 on 2026-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict, help_text='Disponibilidad horaria por día'),
        ),
    ]
