# Generated by Django 5.2.17 on 2026-08-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_teacherprofile_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='additional_areas',
            field=models.JSONField(blank=True, default=list, help_text='Áreas secundarias que puede dictar'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='max_hours',
            field=models.PositiveIntegerField(default=22, help_text='Límite de horas semanales permitidas'),
        ),
    ]
