# Generated by Django 5.2.17 on 2026-08-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_teacherprofile_additional_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='available_shifts',
            field=models.JSONField(blank=True, default=list, help_text="Jornadas disponibles (ej. ['Mañana', 'Tarde'])"),
        ),
    ]
