# Generated by Django 5.2.17 on 2026-08-17 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_teacherprofile_available_shifts'),
        ('curriculum', '0007_course_titular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Año o ciclo lectivo (ej: 2026, 2026-1)', max_length=20)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.course')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_academic_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Académico Docente',
                'verbose_name_plural': 'Historiales Académicos Docentes',
                'db_table': 'academics_teacher_academic_history',
                'ordering': ['-year'],
            },
        ),
    ]
