# Generated by Django 5.2.16 on 2026-08-13 17:44

import apps.institution.domain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Institución Educativa Educk', max_length=255)),
                ('dane_nit', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('academic_year', models.IntegerField(default=2024)),
                ('active_period', models.CharField(default='1er Periodo', max_length=50)),
                ('start_time', models.CharField(default='07:00', max_length=10)),
                ('end_time', models.CharField(default='14:30', max_length=10)),
                ('block_duration_minutes', models.IntegerField(default=45)),
                ('general_scale', models.CharField(default='1.0 - 5.0 (Numérica)', max_length=100)),
                ('decimal_precision', models.IntegerField(default=1)),
                ('min_passing_grade', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('independent_scale_per_level', models.BooleanField(default=False)),
                ('level_scales', models.JSONField(blank=True, default=apps.institution.domain.models.default_level_scales)),
                ('offered_degrees', models.JSONField(blank=True, default=apps.institution.domain.models.default_offered_degrees)),
                ('settings_json', models.JSONField(blank=True, default=apps.institution.domain.models.default_settings_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Institución',
                'verbose_name_plural': 'Configuraciones de Instituciones',
                'db_table': 'institution_settings',
            },
        ),
    ]
