# Generated by Django 5.2.16 on 2026-08-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsetting',
            name='is_formal_education',
            field=models.BooleanField(default=True, help_text='Educación Formal Ley 115 / PEI'),
        ),
    ]
