# Generated by Django 5.2.17 on 2026-08-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institutionsetting_is_formal_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsetting',
            name='shifts',
            field=models.JSONField(blank=True, default=list, help_text="Lista de jornadas con sus horarios. Ej: [{'name': 'Mañana', 'start_time': '07:00', 'end_time': '12:30'}]"),
        ),
    ]
