# Generated by Django 5.2.17 on 2026-08-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_institutionsetting_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsetting',
            name='default_teacher_max_hours',
            field=models.IntegerField(default=22, help_text='Límite máximo de horas semanal predeterminado por docente'),
        ),
    ]
