# Generated by Django 5.2.17 on 2026-08-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_institutionsetting_default_teacher_max_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionsetting',
            name='academic_year',
            field=models.CharField(default='2026', max_length=20),
        ),
    ]
