# Generated by Django 5.2.17 on 2026-08-17 03:21

from django.db import migrations

def update_level_scales(apps, schema_editor):
    InstitutionSetting = apps.get_model('institution', 'InstitutionSetting')
    
    detailed_scales = {
        "preescolar": {
            "type": "Cualitativa (E / S / A / I)",
            "min_passing_grade": "A",
            "equivalences": {
                "excelente": {"label": "E", "description": "Excelente"},
                "sobresaliente": {"label": "S", "description": "Sobresaliente"},
                "aprobado": {"label": "A", "description": "Aceptable"},
                "reprobado": {"label": "I", "description": "Insuficiente"}
            }
        },
        "primaria": {
            "type": "1.0 - 5.0 (Numérica)",
            "min_passing_grade": 3.0,
            "equivalences": {
                "excelente": {"min": 4.6, "max": 5.0},
                "sobresaliente": {"min": 4.0, "max": 4.5},
                "aprobado": {"min": 3.0, "max": 3.9},
                "reprobado": {"min": 1.0, "max": 2.9}
            }
        },
        "secundaria": {
            "type": "1.0 - 5.0 (Numérica)",
            "min_passing_grade": 3.0,
            "equivalences": {
                "excelente": {"min": 4.6, "max": 5.0},
                "sobresaliente": {"min": 4.0, "max": 4.5},
                "aprobado": {"min": 3.0, "max": 3.9},
                "reprobado": {"min": 1.0, "max": 2.9}
            }
        },
        "media": {
            "type": "1.0 - 5.0 (Numérica)",
            "min_passing_grade": 3.0,
            "equivalences": {
                "excelente": {"min": 4.6, "max": 5.0},
                "sobresaliente": {"min": 4.0, "max": 4.5},
                "aprobado": {"min": 3.0, "max": 3.9},
                "reprobado": {"min": 1.0, "max": 2.9}
            }
        }
    }

    for setting in InstitutionSetting.objects.all():
        if isinstance(setting.level_scales, dict):
            updated = False
            new_scales = {}
            for level, scale_info in setting.level_scales.items():
                if isinstance(scale_info, str):
                    if level in detailed_scales:
                        new_scales[level] = detailed_scales[level]
                    else:
                        new_scales[level] = {
                            "type": scale_info,
                            "min_passing_grade": 3.0 if "Numérica" in scale_info else "A",
                            "equivalences": {
                                "excelente": {"min": 4.6, "max": 5.0} if "Numérica" in scale_info else {"label": "E", "description": "Excelente"},
                                "sobresaliente": {"min": 4.0, "max": 4.5} if "Numérica" in scale_info else {"label": "S", "description": "Sobresaliente"},
                                "aprobado": {"min": 3.0, "max": 3.9} if "Numérica" in scale_info else {"label": "A", "description": "Aceptable"},
                                "reprobado": {"min": 1.0, "max": 2.9} if "Numérica" in scale_info else {"label": "I", "description": "Insuficiente"}
                            }
                        }
                    updated = True
                else:
                    new_scales[level] = scale_info
            
            if updated:
                setting.level_scales = new_scales
                setting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_alter_institutionsetting_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(update_level_scales, reverse_code=migrations.RunPython.noop),
    ]
