# Generated by Django 5.2.17 on 2026-08-18 17:42

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PIARDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('student_id', models.UUIDField()),
                ('teacher_id', models.UUIDField()),
                ('pedagogical_strategies', models.TextField(blank=True, help_text='Ajustes y estrategias en el aula')),
                ('learning_rhythm', models.CharField(blank=True, max_length=255)),
                ('medical_diagnosis', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Diagnóstico médico formal (Dato Sensible)')),
                ('clinical_history_notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Notas clínicas anexas (Dato Sensible)')),
            ],
            options={
                'verbose_name': 'PIAR',
                'verbose_name_plural': 'PIARs',
                'db_table': 'support_help_piar',
            },
        ),
    ]
