# Generated by Django 5.2.17 on 2026-08-18 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la falta')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('fault_type', models.CharField(choices=[('TIPO_I', 'Tipo I (Faltas Leves)'), ('TIPO_II', 'Tipo II (Faltas Graves)'), ('TIPO_III', 'Tipo III (Delitos/Extremadamente Graves)')], max_length=20, verbose_name='Clasificación Ley 1620')),
            ],
            options={
                'verbose_name': 'Norma de Convivencia',
                'verbose_name_plural': 'Normas de Convivencia',
                'db_table': 'behavior_rules',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('incident_date', models.DateTimeField(verbose_name='Fecha y hora del incidente')),
                ('location', models.CharField(max_length=255, verbose_name='Lugar del incidente')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Proceso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado del caso')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Reporte de Incidencia',
                'verbose_name_plural': 'Reportes de Incidencias',
                'db_table': 'behavior_incident_reports',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('action_type', models.CharField(choices=[('VERBAL_WARNING', 'Llamado de atención verbal'), ('WRITTEN_WARNING', 'Llamado de atención escrito'), ('PARENT_MEETING', 'Citación a acudiente'), ('COMMITMENT_ACT', 'Acta de compromiso'), ('SUSPENSION', 'Suspensión'), ('EXTERNAL_REFERRAL', 'Remisión a entidad externa (ICBF, Policía)')], max_length=30, verbose_name='Tipo de Acción')),
                ('description', models.TextField(verbose_name='Descripción y conclusiones')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='behavior/actions/', verbose_name='Documento adjunto (PDF)')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_actions_managed', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la acción')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='behavior.incidentreport', verbose_name='Incidente')),
            ],
            options={
                'verbose_name': 'Acción Disciplinaria',
                'verbose_name_plural': 'Acciones Disciplinarias',
                'db_table': 'behavior_disciplinary_actions',
            },
        ),
        migrations.CreateModel(
            name='IncidentInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('role', models.CharField(choices=[('PRESUMED_AGGRESSOR', 'Presunto Agresor'), ('VICTIM', 'Víctima'), ('WITNESS', 'Testigo'), ('OTHER', 'Otro')], max_length=30, verbose_name='Rol en el incidente')),
                ('student_statement', models.TextField(blank=True, verbose_name='Descargos del estudiante')),
                ('rule_broken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='behavior.behaviorrule', verbose_name='Norma infringida')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_involvements', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to='behavior.incidentreport', verbose_name='Incidente')),
            ],
            options={
                'verbose_name': 'Involucrado en Incidente',
                'verbose_name_plural': 'Involucrados en Incidentes',
                'db_table': 'behavior_incident_involvements',
                'unique_together': {('incident', 'student')},
            },
        ),
    ]
