# Generated by Django 5.2.17 on 2026-08-19 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Comunicado')),
                ('body', models.TextField(verbose_name='Cuerpo del mensaje')),
                ('audience_type', models.CharField(choices=[('ALL', 'Toda la Comunidad'), ('PARENTS', 'Padres de Familia'), ('TEACHERS', 'Docentes'), ('STUDENTS', 'Estudiantes')], default='ALL', max_length=20, verbose_name='Público Objetivo')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements_sent', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Comunicado Oficial',
                'verbose_name_plural': 'Comunicados Oficiales',
                'db_table': 'communications_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('notification_type', models.CharField(choices=[('CITATION', 'Citación'), ('ACADEMIC_REPORT', 'Reporte Académico'), ('BEHAVIOR_ALERT', 'Alerta de Convivencia'), ('GENERAL', 'Mensaje General')], default='GENERAL', max_length=20, verbose_name='Tipo de Notificación')),
                ('channel', models.CharField(choices=[('SMS', 'Mensaje de Texto (SMS)'), ('EMAIL', 'Correo Electrónico'), ('IN_APP', 'Notificación en Plataforma')], default='IN_APP', max_length=20, verbose_name='Canal de Envío')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Asunto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Envío'), ('SENT', 'Enviado con Éxito'), ('FAILED', 'Error de Envío')], default='PENDING', max_length=20, verbose_name='Estado del Envío')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de envío')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communications/attachments/')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Remitente (Opcional)')),
            ],
            options={
                'verbose_name': 'Notificación Individual',
                'verbose_name_plural': 'Notificaciones Individuales',
                'db_table': 'communications_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
