# Generated by Django 5.2.16 on 2026-08-14 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=150, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Estudiante',
                'verbose_name_plural': 'Perfiles de Estudiantes',
                'db_table': 'enrollment_student_profiles',
            },
        ),
    ]
