# Generated by Django 5.2.17 on 2026-08-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_studentacademichistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademichistory',
            name='year',
            field=models.CharField(help_text='Año o ciclo lectivo (ej: 2026, 2026-1)', max_length=20),
        ),
    ]
